### ISSUE TITLE
18 validation errors for SensorInfo

### ISSUE THREAD

**Issue by rzarajczyk** [trickeydan/hue2mqtt-python#10] opened 2022-08-27 21:18 UTC
Hi, when I run hue2mqtt (from docker image if this matters) I get the following error:

```2022-08-27 21:13:30 hue2mqtt INFO Hue2MQTT v0.3.1 - Hue to MQTT Bridge.
hue2mqtt_1                            | 2022-08-27 21:13:30 hue2mqtt INFO Connected to MQTT Broker
hue2mqtt_1                            | 2022-08-27 21:13:30 hue2mqtt INFO Connecting to Hue Bridge at 192.168.86.36
hue2mqtt_1                            | 2022-08-27 21:13:31 hue2mqtt INFO Bridge Name: Philips hue
hue2mqtt_1                            | 2022-08-27 21:13:31 hue2mqtt INFO Bridge MAC: 00:17:88:6b:69:b1
hue2mqtt_1                            | 2022-08-27 21:13:31 hue2mqtt INFO API Version: 1.52.0
hue2mqtt_1                            | Traceback (most recent call last):
hue2mqtt_1                            |   File "<string>", line 1, in <module>
hue2mqtt_1                            |   File "/root/.cache/pypoetry/virtualenvs/hue2mqtt-UH3YpJs--py3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
hue2mqtt_1                            |     return self.main(*args, **kwargs)
hue2mqtt_1                            |   File "/root/.cache/pypoetry/virtualenvs/hue2mqtt-UH3YpJs--py3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
hue2mqtt_1                            |     rv = self.invoke(ctx)
hue2mqtt_1                            |   File "/root/.cache/pypoetry/virtualenvs/hue2mqtt-UH3YpJs--py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
hue2mqtt_1                            |     return ctx.invoke(self.callback, **ctx.params)
hue2mqtt_1                            |   File "/root/.cache/pypoetry/virtualenvs/hue2mqtt-UH3YpJs--py3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
hue2mqtt_1                            |     return __callback(*args, **kwargs)
hue2mqtt_1                            |   File "/hue2mqtt-python/hue2mqtt/app.py", line 24, in app
hue2mqtt_1                            |     loop.run_until_complete(hue2mqtt.run())
hue2mqtt_1                            |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
hue2mqtt_1                            |     return future.result()
hue2mqtt_1                            |   File "/hue2mqtt-python/hue2mqtt/hue2mqtt.py", line 109, in run
hue2mqtt_1                            |     await self.main(websession)
hue2mqtt_1                            |   File "/hue2mqtt-python/hue2mqtt/hue2mqtt.py", line 213, in main
hue2mqtt_1                            |     sensor = SensorInfo(id=id, **sensor_raw.raw)
hue2mqtt_1                            |   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
hue2mqtt_1                            | pydantic.error_wrappers.ValidationError: 18 validation errors for SensorInfo
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> presence
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> rotaryevent
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> expectedrotation
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> expectedeventduration
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> buttonevent
hue2mqtt_1                            |   none is not an allowed value (type=type_error.none.not_allowed)
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> dark
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> daylight
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> lightlevel
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> temperature
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> humidity
hue2mqtt_1                            |   field required (type=value_error.missing)
hue2mqtt_1                            | state -> lastupdated
hue2mqtt_1                            |   invalid datetime format (type=value_error.datetime)
hue2mqtt_1                            | state -> open
```

What can I do about it?

**Comment by rzarajczyk** [comment] 2022-08-27 21:26
I will add that after some debugging I found the Hue Dimmer Switch which most probably is causing the problem. 
The `sensor_raw.raw` is:
```
{'state': {'buttonevent': None, 'lastupdated': 'none'}, 'swupdate': {'state': 'noupdates', 'lastinstall': '2020-11-08T00:06:12'}, 'config': {'on': True, 'battery': 100, 'reachable': True, 'pending': []}, 'name': 'Pilot - zapas #1', 'type': 'ZLLSwitch', 'modelid': 'RWL021', 'manufacturername': 'Signify Netherlands B.V.', 'productname': 'Hue dimmer switch', 'diversityid': '73bbabea-3420-499a-9856-46bf437e119b', 'swversion': '6.1.1.28573', 'uniqueid': '00:17:88:01:08:0e:21:6c-02-fc00', 'capabilities': {'certified': True, 'primary': True, 'inputs': [{'repeatintervals': [800], 'events': [{'buttonevent': 1000, 'eventtype': 'initial_press'}, {'buttonevent': 1001, 'eventtype': 'repeat'}, {'buttonevent': 1002, 'eventtype': 'short_release'}, {'buttonevent': 1003, 'eventtype': 'long_release'}, {'buttonevent': 1004, 'eventtype': 'long_press'}]}, {'repeatintervals': [800], 'events': [{'buttonevent': 2000, 'eventtype': 'initial_press'}, {'buttonevent': 2001, 'eventtype': 'repeat'}, {'buttonevent': 2002, 'eventtype': 'short_release'}, {'buttonevent': 2003, 'eventtype': 'long_release'}, {'buttonevent': 2004, 'eventtype': 'long_press'}]}, {'repeatintervals': [800], 'events': [{'buttonevent': 3000, 'eventtype': 'initial_press'}, {'buttonevent': 3001, 'eventtype': 'repeat'}, {'buttonevent': 3002, 'eventtype': 'short_release'}, {'buttonevent': 3003, 'eventtype': 'long_release'}, {'buttonevent': 3004, 'eventtype': 'long_press'}]}, {'repeatintervals': [800], 'events': [{'buttonevent': 4000, 'eventtype': 'initial_press'}, {'buttonevent': 4001, 'eventtype': 'repeat'}, {'buttonevent': 4002, 'eventtype': 'short_release'}, {'buttonevent': 4003, 'eventtype': 'long_release'}, {'buttonevent': 4004, 'eventtype': 'long_press'}]}]}}
```
(this is the output of `print(sensor_raw.raw)`)

**Comment by trickeydan** [comment] 2022-08-27 21:28
Hi @rzarajczyk, this looks like a duplicate of #9.

As a workaround, before I fix the bug (probably tomorrow), try the following:

- Turn off Hue2MQTT
- Reboot Hue Hub
- Press a button on each Hue Dimmer Switch (even off)
- Now start Hue2MQTT

The issue is caused by Hue2MQTT expecting a state for each light switch, but there is no state when the Hub first starts until the switch is pressed.

If this does not work for you, please let me know here.

**Comment by rzarajczyk** [comment] 2022-08-27 21:45
Thanks for immediate response!

The problem is that this Dimmer Switch is a spare/backup one, I don't normally use it... And TBH I don't know where it is (probably somewhere in my drawer). Well I will look for it tomorrow, but the problem is bigger - it's not the only spare Dimmer Switch I have and I'm not able to make sure every one of them is pressed after every Hue hub reboot.

**Closed as completed** 2022-08-28 12:05 UTC

**Comment by trickeydan** [comment] 2022-08-28 12:11
@rzarajczyk This will be fixed in the next release later today.
